### ISSUE TITLE
Implement Bitmap indexing

### ISSUE THREAD

**Issue by nicktripp** [benstoehr/GoldTeamTrack2#15]
@trueb2 More info about this?

**Comment by trueb2** [comment]
**The compensating advantage of bitmap indexes is that they allow us to answer partial-match queries very efficiently in many situations.**  Consider Example 14.41 for a good example of how fast this can be.

Before they are compressed the bitmap indexes require much too much space especially when there are many different values for a field since the total number of bits is the product of the number of records and the number of values.

We will use Run-Length-Encoded bit vectors, all of this is explained in the book in section 14.7. In order to manage a Bitmap index, we need 2 secondary indices (We can use our BTree implementation). 

One is for finding the bit-vectors (think of each bit-vector as a record whose key is the value corresponding to this bit-vector, so any secondary index technique will take us efficiently from values to their bit-vectors.) 

The other is for finding records (once we have determined that we need record k of the data file, how do we find it? We may create another secondary index on the data file, whose search key is the number of the record)
